### ISSUE TITLE
Feature Request: Follow via Email Only

### ISSUE THREAD

**Issue by stephen-hill** [pixelfed/ideas#63]
Hello

I would like members of my family to be able to follow my posts without having to sign-up for an account.

I have many friends and family who will not sign-up for an account or use the PixelDroid app. I know my dad and grandad don't use social networks and email is their main method of online communication.

So I propose a feature where anonymous people can, provided the account is public, subscribe to email notifications of new activity of a specific account.

The email that is sent could be a daily/weekly digest, or an instant email for each post, or this could be configurable.

The person should be able to stop or change their options via a link in the email.

Cheers
Stephen

**Comment by realpixelcode** [comment]
Well, Pixelfed already supports RSS feeds, and many e-mail clients, such as Thunderbird, have corresponding features for subscribing to them. That way, you don't even have to enter your e-mail address anywhere, actually remaining anonymous.

Perhaps your relatives would be comfortable with RSS feeds instead of newsletters.
